name: Build and Deploy
on:
  push:
    branches:
      - release-1.0.1
    paths:
      - "packages/site/**"
  pull_request:
    branches:
      - release-1.0.1
    paths:
      - "packages/site/**"
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install
        run: yarn
        working-directory: ./packages/site

      - name: Build
        run: yarn build
        env:
          REACT_APP_SCAN_SERVER: ${{ secrets.REACT_APP_SCAN_SERVER }}
        working-directory: ./packages/site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./packages/site/build
          CLEAN: true
